# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Test
subtitle: ''
description: ''
keywords:
author: John Doe
language: [ja,en]
timezone: ''

url: https://test.io
root: /
permalink: :language/:year/:month/:day/:title/
new_post_name: :language/:year/:month/:day/:title.md
post_asset_folder: true
per_page: 0
pretty_urls:
  trailing_index: false
  trailing_html: false

theme: singleline

highlight:
  enable: true
  line_number: false

disqus_shortname: hexojs

plugins:
  hexo-multilang:
    # languageと合わせること
    languages: [ja, en]  

    pagination-dir: page

    index-generator:
      per-page: 5
      order-by: -date
      index-dir: 
      default-lang: en

    archive-generator:
      per-page: 10
      order-by: -date
      archives-dir: archives
      yearly: true
      monthly: true
      daily: false

    category-generator:
      per-page: 10
      order-by: -date
      categories-dir: categories
      enable-index-page: true

    tag-generator:
      per-page: 5
      order-by: -date
      tags-dir: tags
      enable-index-page: true